[build]
builder = "dockerfile"
dockerfilePath = "./CarWashBackend/Dockerfile"  # Este es opcional si se usa docker-compose

[deploy]
startCommand = "docker-compose up --build"  # Usa docker-compose para desplegar
restartpolicyType = "always"
healthcheckPath = "/health"
