version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=Carwash_DB;User=root;Password=P@ssWord.123
    depends_on:
      - mysql
    networks:
      - carwash-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: P@ssWord.123
      MYSQL_DATABASE: Carwash_DB
    ports:
      - "3306:3306"
    networks:
      - carwash-network

networks:
  carwash-network:
    driver: bridge
