version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssWord.123
      MYSQL_DATABASE: Carwash_DB
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
    networks:
      - carwash-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carwash_api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql_db;Database=Carwash_DB;User=root;Password=P@ssWord.123
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "80:80"
    networks:
      - carwash-network

networks:
  carwash-network:
    driver: bridge
