version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssWord.123
      MYSQL_DATABASE: Carwash_DB
      TZ: America/Tegucigalpa  # Configurar la zona horaria de Honduras
    command: --default-time-zone='-06:00'  # Forzar UTC -6 en MySQL
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Persistencia de datos
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
    networks:
      - carwash-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carwash_api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MYSQL_HOST=mysql_db
      - MYSQL_DATABASE=Carwash_DB
      - MYSQL_USER=root
      - MYSQL_PASSWORD=P@ssWord.123
      - PORT=80
    depends_on:
      mysql:
        condition: service_healthy
    command: >
      sh -c "echo 'Esperando a que MySQL esté disponible...';
             while ! nc -z mysql_db 3306; do sleep 1; done;
             echo 'MySQL está listo';
             dotnet CarWashBackend.dll"
    ports:
      - "8081:80"
    networks:
      - carwash-network

networks:
  carwash-network:
    driver: bridge

volumes:
  mysql_data:  # Definir el volumen
