version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssWord.123
      MYSQL_DATABASE: Carwash_DB
      MYSQL_USER: root
      MYSQL_PASSWORD: P@ssWord.123
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
    networks:
      - carwash-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carwash_api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MYSQL_HOST=mysql_db
      - MYSQL_DATABASE=Carwash_DB
      - MYSQL_USER=root
      - MYSQL_PASSWORD=P@ssWord.123
    depends_on:
      mysql:
        condition: service_healthy
    command: >
      sh -c "echo 'Esperando a que MySQL esté disponible...';
             while ! bash -c 'echo > /dev/tcp/mysql_db/3306' 2>/dev/null; do sleep 1; done;
             echo 'MySQL está listo';
             dotnet CarWashBackend.dll"
    ports:
      - "80:80"
    networks:
      - carwash-network

networks:
  carwash-network:
    driver: bridge
