version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DB_CONNECTION_STRING=Server=mysql;Database=Carwash_DB;User=root;Password=P@ssWord.123
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "5000:80"
    entrypoint: >
      sh -c "
      echo 'Esperando a MySQL...';
      until dotnet ef database update; do
        echo 'Reintentando migración...';
        sleep 2;
      done;
      exec dotnet CarWashBackend.dll"

  mysql:
    image: mysql:8.0
    container_name: mysql_carwash
    environment:
      MYSQL_ROOT_PASSWORD: "P@ssWord.123"
      MYSQL_DATABASE: "Carwash_DB"
    ports:
      - "3306:3306"
    volumes:
      - carwash_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=localhost", "--user=root", "--password=P@ssWord.123"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

volumes:
  carwash_db_data:
