// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarWashBackend.Models;

public partial class Pago
{
    public string id { get; set; }

    public string registro_servicio_id { get; set; }

    public decimal monto { get; set; }

    public string metodo_pago { get; set; }

    public DateTime? fecha { get; set; }

    public DateTime? created_at { get; set; }

    public DateTime? updated_at { get; set; }

    public virtual RegistroServicio registro_servicio { get; set; }
}