// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarWashBackend.Models;

public partial class registro_servicio_detalle
{
    public string id { get; set; }

    public string registro_servicio_vehiculo_id { get; set; }

    public string servicio_id { get; set; }

    public decimal precio { get; set; }

    public virtual registro_servicio_vehiculo registro_servicio_vehiculo { get; set; }

    public virtual Servicio servicio { get; set; }
}