// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarWashBackend.Models;

public partial class RegistroServicio
{
    public string id { get; set; }

    public string cliente_id { get; set; }

    public string vehiculo_id { get; set; }

    public string servicio_id { get; set; }

    public string usuario_id { get; set; }

    public string estado_id { get; set; }

    public string observaciones { get; set; }

    public DateTime? fecha { get; set; }

    public DateTime? created_at { get; set; }

    public DateTime? updated_at { get; set; }

    public virtual ICollection<Pago> Pagos { get; set; } = new List<Pago>();

    public virtual Cliente cliente { get; set; }

    public virtual EstadosServicio estado { get; set; }

    public virtual Servicio servicio { get; set; }

    public virtual Usuario usuario { get; set; }

    public virtual Vehiculo vehiculo { get; set; }
}