// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarWashBackend.Models;

public partial class registro_servicio_vehiculo
{
    public string id { get; set; }

    public string registro_servicio_id { get; set; }

    public string vehiculo_id { get; set; }

    public virtual registro_servicio registro_servicio { get; set; }

    public virtual ICollection<registro_servicio_detalle> registro_servicio_detalles { get; set; } = new List<registro_servicio_detalle>();

    public virtual Vehiculo vehiculo { get; set; }
}