// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarWashBackend.Models;

public partial class Usuario
{
    public string id { get; set; }

    public string usuario1 { get; set; }

    public string contrasena { get; set; }

    public string empleado_id { get; set; }

    public DateTime? created_at { get; set; }

    public DateTime? updated_at { get; set; }

    public string role_id { get; set; }

    public bool? activo { get; set; }

    public virtual Empleado empleado { get; set; }

    public virtual Role role { get; set; }
}