// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarWashBackend.Models;

public partial class Role
{
    public string id { get; set; }

    public string nombre { get; set; }

    public string descripcion { get; set; }

    public DateTime? created_at { get; set; }

    public DateTime? updated_at { get; set; }

    public virtual ICollection<Permiso> permisos { get; set; } = new List<Permiso>();

    public virtual ICollection<Usuario> usuarios { get; set; } = new List<Usuario>();
}